import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Navbar from "@/component/Navber";
import Header from "@/component/Header";
import Footer from "@/component/Footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../public/style/style.css";
import "../public/style/blog_style.css/";
import "../public/style/bootstrp.min.css";
// import "../public/style/font-awesome.css";
// import "../public/style/font-awesome.min.css";
import "../public/style/mobileView.css";
import "../public/style/navbar.css";
// import "../style/remixicon.css";
import "../public/style/services_all_detsilss.css";

// import "../app/style/mobileView.css";
// import "../app/style/font-awesome.min.css";
// import "../app/style/font-awesome.css";
// import "../app/style/bootstrp.min.css";
// import "../app/style/blog_style.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Welcome to Sinclair McKinsley - Your Financial Partner",
  description: "Generated by create next app",
  icons: {
    icon: "../asset/favicon.jpeg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}`}>
        className={` ${poppins.variable}`}>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
